spring:
  sbp:
    runtime-mode: deployment # development, deployment
    enabled: true
    classes-directories:
      - "build/classes"
      - "build/resources"
    lib-directories:
      - "libs"
    plugins-root: /home/guqing/Developer/plugins
    controller:
      base-path: sbp
  #    custom-plugin-loaders:
  #      - demo.sbp.app.CustomPluginLoader
  main:
    allow-bean-definition-overriding: true

